### PR TITLE
Removing log out/opt in/out tests

### PR DESCRIPTION
**Pull request by ironsidevsquincy**
As moved to pingdom transactions

https://my.pingdom.com/newchecks/transactions#check=t32882
https://my.pingdom.com/newchecks/transactions#check=t32880

### CODE REVIEW

**Comment by matthew-andrews** [comment]
i think they should still be platinum alerts for this, but otherwise +1

**Comment by matthew-andrews** [comment]
ah one of them is one of them is bronze, is that correct?

**Comment by ironsidevsquincy** [comment]
Yep, that's what it is currently

**Comment by matthew-andrews** [comment]
cool

**Comment by matthew-andrews** [comment]
+1

**Pull request merged**
