### PR TITLE
Add pingdom health checks for articles

### PR DESCRIPTION
**Pull request by imranolas**
@adgad @matthew-andrews: Any other checks you think should be added here?

### CODE REVIEW

**Comment by matthew-andrews** [comment]
Hmm I realise this isn't very clear but it's actually not necessary to add Pingdom checks to the health app… they can just directly be assigned to the ‘Next PagerDuty  — platinum’ escalation policy.

**Comment by matthew-andrews** [comment]
What we mean by health checks is checks within an app to ensure that it thinks it has everything it needs / can talk to all the services it need to talk to:-
e.g.
https://github.com/Financial-Times/next-harrier/blob/master/server/app.js#L14-L15
http://ft-next-article.herokuapp.com/__health

**Comment by matthew-andrews** [comment]
https://ft-next-harrier-eu.herokuapp.com/__healthhttps://ft-next-harrier-eu.herokuapp.com/__health

**Comment by imranolas** [comment]
Ah, Got it. Thanks for clarifying.

**Comment by matthew-andrews** [comment]
I've added an issue to think about this: https://github.com/Financial-Times/next-health/issues/37

**Pull request closed without merging**
